#!/bin/bash
echo "Number of Directories (~Class) : "`(find src -type d | wc -l)`
echo "Number of Files                : "`(find src -type f | wc -l)`
echo "Number of lines Code           : "`(( find src \( -name '*.*' -o -name 'Makefile' \) -print0 | xargs -0 cat ) | wc -l)`
